language: java

branches:
  except:
    - /dev-build-.*/

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=dev-build-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER on $(date -u "+%Y-%m-%d-%H-%M-%S")"
  - git push --quiet origin $GIT_TAG

deploy:
  - provider: releases
    prerelease: true
    api_key: $AUTH_TOKEN
    file: "dist/PhatLoots.jar"
    skip_cleanup: true
    on:
      branch: master
      tags: false
  - provider: releases
    prerelease: false
    api_key: $AUTH_TOKEN
    file: "dist/PhatLoots.jar"
    skip_cleanup: true
    on:
      tags: true
