name: PhatLoots
main: PhatLoots.PhatLootsMain
version: 1.0.0
author: Codisimus
website: www.codisimus.com
description: Chestsr with randomly generated money/items
commands:
  loot:
    description: Main command, type for additional help/commands